# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-05 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIdashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apis',
            old_name='request',
            new_name='requesting',
        ),
    ]
